# Node surumunu belirliyoruz
FROM node:22.14.0-alpine AS base

# Uygulama dizinini belirliyoruz
WORKDIR /usr/src/app

# Uygulama dosyalarını kopyalıyoruz ve kullanılan paketleri yukluyoruz
FROM base AS dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

# Uygulama kodlarini kopyalıyoruz
FROM base AS release
WORKDIR /usr/src/app
COPY --from=dependencies /usr/src/app/node_modules ./node_modules
COPY src/ .

# Calisacak portu belirliyoruz
EXPOSE 3000

# Uygulamayı calistiriyoruz
CMD ["node", "src/server.js"]